In [3]:
import numpy as np
from keras.layers import Dense
from keras.models import Sequential
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [4]:
bits=8

In [5]:
def gennos(v):
    x1=[]
    for i in range(254):
        y1=[]
        z=bin(i + v)[2:].zfill(bits)
        for j in z:
            y1.append(int(j))
        x1.append(y1)
    return np.array(x1)

In [6]:
def dataset():
    return gennos(0),gennos(1)

In [7]:
x2,y2=dataset()
X_train,X_test,Y_train,Y_test = train_test_split(x2,y2,test_size=0.28,random_state=42)

In [8]:
print(X_train,Y_train)
print(X_test,Y_test)
print(X_train.shape,Y_train.shape)

[[1 0 0 ..., 1 0 1]
 [0 1 1 ..., 1 0 1]
 [0 1 1 ..., 0 1 1]
 ..., 
 [0 1 0 ..., 1 0 0]
 [1 0 1 ..., 0 1 1]
 [0 1 1 ..., 1 1 0]] [[1 0 0 ..., 1 1 0]
 [0 1 1 ..., 1 1 0]
 [0 1 1 ..., 1 0 0]
 ..., 
 [0 1 0 ..., 1 0 1]
 [1 0 1 ..., 1 0 0]
 [0 1 1 ..., 1 1 1]]
[[1 0 1 1 1 1 1 0]
 [0 0 0 0 0 1 1 0]
 [0 1 0 0 1 1 1 1]
 [1 1 0 0 1 1 0 1]
 [0 1 1 1 0 1 0 1]
 [1 0 1 1 1 0 0 1]
 [1 1 0 0 1 0 0 1]
 [1 0 1 0 0 1 1 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 1 1 1 1 0]
 [1 0 1 1 0 1 0 0]
 [1 1 0 1 1 1 0 0]
 [1 1 1 0 0 1 0 0]
 [1 1 0 1 1 0 0 0]
 [1 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0 0]
 [1 1 0 0 0 1 1 0]
 [0 0 0 0 1 1 1 1]
 [0 1 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [1 1 1 0 1 0 0 1]
 [0 0 0 1 0 0 1 1]
 [0 1 1 1 1 0 0 0]
 [1 0 0 1 1 0 0 0]
 [0 0 1 0 0 0 0 1]
 [0 1 1 1 1 1 0 0]
 [1 1 1 1 1 0 1 1]
 [1 1 1 1 0 0 1 0]
 [0 0 0 0 1 0 1 0]
 [1 0 1 0 0 1 0 0]
 [1 0 1 1 1 0 0 0]
 [0 1 1 0 0 0 0 1]
 [1 0 0 1 0 1 0 0]
 [1 1 0 1 0 0 0 1]
 [1 1 0 1 1 1 0 1]
 [0 0 0 1 1 0 0 1]
 [0 1 0 1 0 1 1 0]
 [0 0 0 1 0 0 1 0]
 [0 1 0 0 1 0 1 1]
 [1

In [10]:
model=Sequential()
model.add(Dense(units=128,input_dim=bits,activation='sigmoid'))
model.add(Dense(units=64,activation='sigmoid'))
model.add(Dense(units=bits,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,Y_train,epochs=500,batch_size=5)

Epoch 1/500
182/182 [==============================] - 1s 4ms/step - loss: 0.6997 - acc: 0.5000
Epoch 2/500
182/182 [==============================] - 0s 278us/step - loss: 0.6939 - acc: 0.5007
Epoch 3/500
182/182 [==============================] - 0s 277us/step - loss: 0.6879 - acc: 0.5240
Epoch 4/500
182/182 [==============================] - 0s 281us/step - loss: 0.6861 - acc: 0.5646
Epoch 5/500
182/182 [==============================] - 0s 281us/step - loss: 0.6806 - acc: 0.5646
Epoch 6/500
182/182 [==============================] - 0s 305us/step - loss: 0.6735 - acc: 0.6298
Epoch 7/500
182/182 [==============================] - 0s 287us/step - loss: 0.6676 - acc: 0.6168
Epoch 8/500
182/182 [==============================] - 0s 302us/step - loss: 0.6630 - acc: 0.6442
Epoch 9/500
182/182 [==============================] - 0s 285us/step - loss: 0.6505 - acc: 0.6937
Epoch 10/500
182/182 [==============================] - 0s 275us/step - loss: 0.6451 - acc: 0.6971
Epoch 11/500
182/182 

182/182 [==============================] - 0s 286us/step - loss: 0.2302 - acc: 0.8860
Epoch 84/500
182/182 [==============================] - 0s 282us/step - loss: 0.2281 - acc: 0.8832
Epoch 85/500
182/182 [==============================] - 0s 255us/step - loss: 0.2269 - acc: 0.8826
Epoch 86/500
182/182 [==============================] - 0s 293us/step - loss: 0.2257 - acc: 0.8887
Epoch 87/500
182/182 [==============================] - 0s 278us/step - loss: 0.2235 - acc: 0.8860
Epoch 88/500
182/182 [==============================] - 0s 289us/step - loss: 0.2233 - acc: 0.8846
Epoch 89/500
182/182 [==============================] - 0s 273us/step - loss: 0.2215 - acc: 0.8901
Epoch 90/500
182/182 [==============================] - 0s 283us/step - loss: 0.2208 - acc: 0.8839
Epoch 91/500
182/182 [==============================] - 0s 270us/step - loss: 0.2192 - acc: 0.8942
Epoch 92/500
182/182 [==============================] - 0s 275us/step - loss: 0.2179 - acc: 0.8901
Epoch 93/500
182/182 [=

182/182 [==============================] - 0s 264us/step - loss: 0.1001 - acc: 0.9560
Epoch 166/500
182/182 [==============================] - 0s 275us/step - loss: 0.0989 - acc: 0.9574
Epoch 167/500
182/182 [==============================] - 0s 287us/step - loss: 0.0974 - acc: 0.9609
Epoch 168/500
182/182 [==============================] - 0s 258us/step - loss: 0.0964 - acc: 0.9609
Epoch 169/500
182/182 [==============================] - 0s 294us/step - loss: 0.0948 - acc: 0.9602
Epoch 170/500
182/182 [==============================] - 0s 250us/step - loss: 0.0938 - acc: 0.9622
Epoch 171/500
182/182 [==============================] - 0s 279us/step - loss: 0.0923 - acc: 0.9629
Epoch 172/500
182/182 [==============================] - 0s 270us/step - loss: 0.0908 - acc: 0.9657
Epoch 173/500
182/182 [==============================] - 0s 289us/step - loss: 0.0903 - acc: 0.9650
Epoch 174/500
182/182 [==============================] - 0s 283us/step - loss: 0.0890 - acc: 0.9684
Epoch 175/500


182/182 [==============================] - 0s 280us/step - loss: 0.0322 - acc: 0.9904
Epoch 248/500
182/182 [==============================] - 0s 309us/step - loss: 0.0317 - acc: 0.9897
Epoch 249/500
182/182 [==============================] - 0s 276us/step - loss: 0.0313 - acc: 0.9924
Epoch 250/500
182/182 [==============================] - 0s 281us/step - loss: 0.0307 - acc: 0.9911
Epoch 251/500
182/182 [==============================] - 0s 253us/step - loss: 0.0306 - acc: 0.9924
Epoch 252/500
182/182 [==============================] - 0s 277us/step - loss: 0.0304 - acc: 0.9911
Epoch 253/500
182/182 [==============================] - 0s 261us/step - loss: 0.0299 - acc: 0.9911
Epoch 254/500
182/182 [==============================] - 0s 308us/step - loss: 0.0293 - acc: 0.9924
Epoch 255/500
182/182 [==============================] - 0s 283us/step - loss: 0.0291 - acc: 0.9924
Epoch 256/500
182/182 [==============================] - 0s 277us/step - loss: 0.0285 - acc: 0.9918
Epoch 257/500


182/182 [==============================] - 0s 302us/step - loss: 0.0107 - acc: 0.9973
Epoch 330/500
182/182 [==============================] - 0s 278us/step - loss: 0.0104 - acc: 0.9973
Epoch 331/500
182/182 [==============================] - 0s 272us/step - loss: 0.0102 - acc: 0.9973
Epoch 332/500
182/182 [==============================] - 0s 275us/step - loss: 0.0101 - acc: 0.9973
Epoch 333/500
182/182 [==============================] - 0s 272us/step - loss: 0.0102 - acc: 0.9979
Epoch 334/500
182/182 [==============================] - 0s 289us/step - loss: 0.0098 - acc: 0.9973
Epoch 335/500
182/182 [==============================] - 0s 270us/step - loss: 0.0097 - acc: 0.9973
Epoch 336/500
182/182 [==============================] - 0s 296us/step - loss: 0.0096 - acc: 0.9973
Epoch 337/500
182/182 [==============================] - 0s 254us/step - loss: 0.0094 - acc: 0.9973
Epoch 338/500
182/182 [==============================] - 0s 275us/step - loss: 0.0093 - acc: 0.9973
Epoch 339/500


182/182 [==============================] - 0s 302us/step - loss: 0.0029 - acc: 1.0000
Epoch 412/500
182/182 [==============================] - 0s 319us/step - loss: 0.0028 - acc: 1.0000
Epoch 413/500
182/182 [==============================] - 0s 315us/step - loss: 0.0028 - acc: 1.0000
Epoch 414/500
182/182 [==============================] - 0s 299us/step - loss: 0.0028 - acc: 1.0000
Epoch 415/500
182/182 [==============================] - 0s 319us/step - loss: 0.0027 - acc: 1.0000
Epoch 416/500
182/182 [==============================] - 0s 319us/step - loss: 0.0026 - acc: 1.0000
Epoch 417/500
182/182 [==============================] - 0s 308us/step - loss: 0.0026 - acc: 1.0000
Epoch 418/500
182/182 [==============================] - 0s 308us/step - loss: 0.0025 - acc: 1.0000
Epoch 419/500
182/182 [==============================] - 0s 308us/step - loss: 0.0025 - acc: 1.0000
Epoch 420/500
182/182 [==============================] - 0s 313us/step - loss: 0.0025 - acc: 1.0000
Epoch 421/500


182/182 [==============================] - 0s 302us/step - loss: 6.4695e-04 - acc: 1.0000
Epoch 493/500
182/182 [==============================] - 0s 296us/step - loss: 6.3483e-04 - acc: 1.0000
Epoch 494/500
182/182 [==============================] - 0s 283us/step - loss: 6.2104e-04 - acc: 1.0000
Epoch 495/500
182/182 [==============================] - 0s 270us/step - loss: 6.1423e-04 - acc: 1.0000
Epoch 496/500
182/182 [==============================] - 0s 281us/step - loss: 6.0115e-04 - acc: 1.0000
Epoch 497/500
182/182 [==============================] - 0s 300us/step - loss: 5.8657e-04 - acc: 1.0000
Epoch 498/500
182/182 [==============================] - 0s 250us/step - loss: 5.7217e-04 - acc: 1.0000
Epoch 499/500
182/182 [==============================] - 0s 272us/step - loss: 5.5949e-04 - acc: 1.0000
Epoch 500/500
182/182 [==============================] - 0s 278us/step - loss: 5.5014e-04 - acc: 1.0000


In [17]:
model.evaluate(X_test,Y_test,verbose=1,batch_size=128)

72/72 [==============================] - 0s 0us/step


[0.052295513451099396, 0.98958331346511841]

In [20]:
def next(val):
    if val <= 254:
        out_l = []
        inp_l = []
        b = bin(val)[2:].zfill(8)
        for k in b:
            inp_l.append(int(k))
        out_l.append(inp_l)
        out_l = np.array(out_l)
        classes = model.predict(out_l)
        output = []
        for u in classes:
            li = []
            for z in u:
                if z >= 0.1:
                    li.append(1)
                else:
                    li.append(0)
            output.append(li)
        output = np.array(output)
        print("Input:", out_l, "output:", output)
    else:
        print("Exceeds")

In [22]:
a1=int(input("Enter a NO:"))
next(a1)

Enter a NO:182
Input: [[1 0 1 1 0 1 1 0]] output: [[1 0 1 1 0 1 1 1]]
